# NumPy
## What is NumPy?

- Python에서 scientific computing을 하기 위한 기본 패키지
- 다차원 배열 객체와 빠른 계산을 제공함
- 가장 중심이 되는 건 `ndarray`(N-dimensional Array)라는 클래스로 단일 타입으로 된 n 차원 배열을 담을 수 있으며, 속도 개선을 위해 컴파일 된 코드로 계산이 실행됨.
- 파이썬의 연속성 데이터와 다른 점은
    - 파이썬 리스트와 다르게 NumPy 배열은 고정된 크기로 생성됩니다. 사이즈의 변경을 위해서는 기존 배열을 삭제하고 새로운 배열을 생성하는 방식이 됩니다.
    - NumPy 배열의 모든 원소는 메모리 상에서 모두 동일한 자리를 차지해야 하기 때문에 동일한 데이터 타입이어야 합니다. 단, 종종 파이썬 리스트 자체를 원소로 사용하는 NumPy 배열은 실제로는 데이터의 포인터만을 원소로 가지기 때문에 크기가 다른 데이터를 가지고 있는 것처럼 보이기도 합니다.
    - 대규모 연산에 적합합니다.

- 만약 두 배열의 요소를 각각 곱한다고 생각해봅시다.
  - 파이썬에서는 리스트 a와 리스트 b의 곱을 다음과 같이 수행합니다.
    
      ---
      ```python
      c = []
      for i in range(len(a)):
          c.append(a[i] * b[i])
      ```
      ---
    이 코드는 물론 올바른 답을 산출하겠지만, 시간 복잡도 $O(n)$이기 때문에, a와 b가 각각 몇 백만개의 데이터를 가지고 있다면, 당연히 비효율성의 극치입니다.
        
  - 만약 C 언어라면 다음과 같이 작성합니다.
      
      ---
      ```c
      for (i = 0; i < rows; i++) {
        c[i] = a[i]*b[i];
      }
      ```
      ---
      
      파이썬의 경우 동일한 반복문을 돌리더라도, 매 회차 i가 어떤 숫자인지, 얼마인지, a[i]의 데이터 형이 무엇인지, 이걸 계산을 할 수 있는지 등 모든 것에 대해서 검증한 후 한 번의 계산을 진행합니다. 반면, C 언어에서는 그러한 과정을 `컴파일`이라는 과정 중에 다 완료하고 단순하게 계산만 진행하기 때문에 C 언어의 코드가 파이썬과 거의 비슷한 형태로 이뤄져 있더라도, 속도에서는 엄청난 차이가 납니다. 다만, 파이썬의 편의성을 그 대가로 지불하죠.
      
      또, 아무리 빠르더라도, 차원이 늘어날 수록 코드는 더 늘어나야 합니다. 2 차원 배열의 계산을 위해서는 다음과 같이 짜야 합니다.
      
      ---
      ```c
      for (i = 0; i < rows; i++) {
        for (j = 0; j < columns; j++) {
          c[i][j] = a[i][j]*b[i][j];
        }
      }
      ```
      ---
        
  - NumPy는 이런 두 언어의 장점을 합쳤습니다. `ndarray`를 활용한 연산에서는 단순히 * 기호를 쓰는 것만으로 요소별 곱 연산을 자동적으로 적용하며, 이러한 곱은 미리 컴파일된 C 언어를 사용하기 때문에, 매우 빠릅니다.
      
      ---
      ```python
      c = a * b
      ```
      ---

## Why is NumPy fast?

벡터화한다는 것은 코드 내에서 반복문이나 인덱싱이 없다는 것을 의미하고, C 언어의 사전 컴파일링을 통해 최적화될 수 있습니다. 또한 다음의 이점들이 존재합니다.

- 벡터화된 코드는 더 간결하고 읽기 쉽습니다.
- 보통 더 적은 줄의 코드는 더 적은 버그로 이어집니다.
- 코드를 더 수학적으로 구성하기 때문에 일반 수학의 기법을 적용하기 쉽습니다.
- 더 파이썬 같은 코드를 제공합니다. 벡터화가 없었으면 더 복잡한 코드가 되었을 겁니다.

또한 브로드캐스팅이라는 기능을 사용합니다. 브로드캐스팅은 각 요소간 연산을 위한 암묵적인 룰로, 예를 들어 동일한 차원의 행렬의 합은 요소의 위치가 명확하기 때문에 명확하게 계산할 수 있지만.

In [32]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

c = a + b

In [33]:
a

array([1, 2, 3])

In [34]:
b

array([3, 2, 1])

In [35]:
c

array([4, 4, 4])

그렇지 않은 경우에는 NumPy가 자체적으로 이를 차원 확장시켜 계산합니다.

In [36]:
import numpy as np

a = np.array([1, 2, 3])
b = 4

c = a + b

In [37]:
a

array([1, 2, 3])

In [38]:
b

4

In [39]:
c

array([5, 6, 7])

In [40]:
import numpy as np

# 1x3 Array
a = np.array([1, 2, 3]) 

# 3x1 Array
b = np.array([[10],
              [20],
              [30]])

c = a + b

In [41]:
a

array([1, 2, 3])

In [42]:
a.shape

(3,)

In [43]:
b

array([[10],
       [20],
       [30]])

In [44]:
b.shape

(3, 1)

In [45]:
c

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [46]:
c.shape

(3, 3)

## NumPy quickstart

### The basics

- NumPy에서 주요하게 다루는 요소는 단일 타입으로 이뤄진 다차원 배열입니다. 일반적으로 숫자 같은 하나의 타입으로 이뤄진 배열은 정수 인덱스를 가지고, NumPy의 차원은 `axes`라는 명칭으로 부릅니다.
- 예를 들어, 3차원 좌표계의 한 점을 나타내는 
`[1, 2, 1]`의 경우 하나의 axis를 가집니다 (axis = 1). 또한 3개의 요소를 가지기 때문에, 길이는 3이죠 (length = 3).
- 만약 다음과 같은 배열이 있다면,
`[[1., 0., 0.],
[0., 1., 2.]]`
이 배열은 axis = 2 이고, length = 3 입니다.
- NumPy의 배열 클래스는 `ndarray`라고 부르며, `array`의 동치이기도 합니다. 다만, 파이썬의 `array.array` 클래스와는 전혀 다릅니다 (`array.array`는 1 차원의 배열만 다루고 더 적은 기능을 제공).

- ndarray에 포함된 다양한 메서드를 알아봅시다.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])

b = np.array([[1, 2, 3],
              [4, 5, 6]])

c = np.array([[[1, 2, 3],
               [4, 5, 6]],

              [[7, 8, 9],
               [10, 11, 12]]])

- `ndarray.ndim`: ndarray의 차원을 반환합니다.

In [ ]:
a.ndim # 1차원 배열

1

In [ ]:
b.ndim # 2차원 배열

2

In [53]:
c.ndim # 3차원 배열

3

- `ndarray.shape`: 각 차원별 ndarray의 크기를 튜플 형태로 반환합니다.

In [ ]:
print(a.shape) # (3,) : 1차원 배열, 요소가 3개

(3,)


In [ ]:
print(b.shape) # (2, 3) : 2차원 배열, 2행 3열

(2, 3)


In [58]:
print(c.shape) # (2, 2, 3) : 3차원 배열, 2개의 2행 3열 배열

(2, 2, 3)


- `ndarray.size`: ndarray에 포함된 총 원소의 개수를 반환합니다.

In [59]:
print(a.size) # 3 : 요소의 개수

3


In [60]:
print(b.size) # 6 : 요소의 개수

6


In [61]:
print(c.size) # 12 : 요소의 개수

12


- `ndarray.dtype`: ndarray를 이루고 있는 원소의 데이터 타입을 반환합니다. 파이썬에 있는 데이터 타입 또는 NumPy의 자체 타입인, numpy.int32, numpy,int16, 그리고 numpy.float64 등이 포함됩니다.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])

b = np.array([[1., 2., 3.],
              [4., 5., 6.]])

c = np.array([[['01', '02', '03'],
               ['04', '05', '06']],

              [['07', '08', '09'],
               ['10', '11', '12']]])

d = np.array([[['1', '2', '3'],
               ['4', '5', '6']],
               
              [['7', '8', '9'],
               ['0', '0', '0']]])

In [64]:
a.dtype # int64

dtype('int64')

In [65]:
b.dtype # float64

dtype('float64')

In [66]:
c.dtype # <U2

dtype('<U2')

In [67]:
d.dtype # <U1

dtype('<U1')

- `ndarray.itemsize`: ndarray를 이루고 있는 각 원소의 메모리 상의 사이즈를 반환합니다.

In [68]:
a.itemsize # 8 : int64는 8바이트

8

In [69]:
b.itemsize # 8 : float64는 8바이트

8

In [70]:
c.itemsize # 4 : <U2는 4바이트 (문자열의 길이 2 + null 문자)

8

In [71]:
d.itemsize # 4 : <U1는 4바이트 (문자열의 길이 1 + null 문자)

4

- `ndarray.data`: 메모리 상에 ndarray가 저장된 실체 위치값을 반환합니다. 우리는 어차피 인덱스를 통해서 각 요소에 접근하기 때문에 실제 ndarray가 메모리 어디에 위치하는지는 딱히 알 필요성이 없습니다.

In [72]:
a.data # 메모리 상에 a가 저장된 실체 위치값

- `numpy.arange([*start*, ]*stop*, [*step*, ]*dtype=None*, ***, *device=None*, *like=None*)`: start (없으면 0)부터 stop까지를 step (없으면 1) 간격으로 균일하게 배치해 이뤄진 ndarray를 반환합니다.

In [ ]:
import numpy as np

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- `ndarray.reshape(*shape*, */*, ***, *order='C'*, *copy=None)`:* 대상이 된 ndarray를 shape에 맞게 변형합니다. 원칙적으로 ndarray.reshape((a, b))로 쓰는게 맞으나, ndarray.reshape(a, b)를 허용합니다.

In [74]:
a.reshape(3, 5) # 3행 5열로 재구성

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Array Creation

- numpy의 ndarray를 생성하는 방식을 알아봅시다.

#### numpy.array

##### 파이썬의 1차원 리스트나 튜플로부터 `numpy.array` 함수를 사용하는 방법

In [8]:
import numpy as np

a = [2, 3, 4]
a_array = np.array(a)

In [9]:
a_array

array([2, 3, 4])

In [10]:
a_array.dtype

dtype('int64')

In [11]:
import numpy as np

b = [1.2, 3.5, 5.1]
b_array = np.array(b)

In [12]:
b_array

array([1.2, 3.5, 5.1])

In [13]:
b_array.dtype

dtype('float64')

##### 파이썬의 1차원 리스트 및 튜플을 복수로 받아 `numpy.array`를 사용하는 방법

In [14]:
import numpy as np

a = (1.5, 2, 3)
b = (4, 5, 6)
c = np.array([a, b])
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

##### 생성 시에 타입을 명시하는 방법

In [15]:
d = np.array([a, b], dtype=complex)
d

array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

complex 타입은 실수부와 허수부로 구성된 복소수(complex number)를 나타내는 데이터 타입입니다. 예를 들어, 1 + 2j는 실수부가 1이고 허수부가 2인 복소수를 나타냅니다. NumPy에서는 complex 타입을 사용하여 복소수 배열을 생성할 수 있습니다.

- 때로는 array의 사이즈는 알지만 원소를 모를 때가 있습니다. NumPy에서는 이런 경우를 위해 array의 자리만 만들어 놓고 우선 원소는 비워놓는 방식의 기능도 존재합니다.

#### `numpy.zeros`: 모든 원소가 0인 배열을 생성합니다.

In [16]:
import numpy as np

zero_array = np.zeros((3, 4))
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### `numpy.ones`: 모든 원소가 1인 배열을 생성합니다.

In [17]:
import numpy as np

one_array = np.ones((2, 3, 4))
one_array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

#### `numpy.empty`: 배열의 크기만 지정하고 초기화하지 않은 배열을 생성합니다. 배열의 원소는 초기화되지 않으므로 이전 메모리 값이 그대로 남아 있을 수 있습니다.

In [18]:
import numpy as np

empty_array = np.empty((2, 3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

#### numpy.*_like
또한 기준 배열이 있다면, 해당 기준 배열의 성격과 동일한, ones, zeros, empty를 생성할 수 있습니다. 다음 3 가지 함수는 모두 `standard_array`와 동일한 shape과 dtype을 가지는 배열을 생성합니다.
- `numpy.ones_like(standard_array)`
- `numpy.zeros_like(standard_array)`
- `numpy.empty_like(standard_array)`

또는 파이썬의 range 함수와 비슷한 기능을 통해 범위에 맞춰 규칙적인 간격으로 이뤄진 array를 만들 수도 있습니다.

#### numpy.arange(start, end, step)

In [19]:
import numpy as np

a = np.arange(10, 30, 5)
print(a) # [10 15 20 25]

b = np.arange(0, 2, 0.3)
print(b) # [0.  0.3 0.6 0.9 1.2 1.5 1.8]

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


#### numpy.linspace(start, end, number)
종종 부동 소수점 오차에 의해 실수 범위에서 사용하는 arange는 마지막 범위가 포함될지 안 될지 다소 모호한 경향이 있습니다. 때문에 linspace를 사용합니다.


In [20]:
import numpy as np
from numpy import pi

a = np.linspace(0, 2, 9)
print(a) # [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

x = np.linspace(0, 2 * pi, 20)
f = np.sin(x)
print(f)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.00000000e+00  3.24699469e-01  6.14212713e-01  8.37166478e-01
  9.69400266e-01  9.96584493e-01  9.15773327e-01  7.35723911e-01
  4.75947393e-01  1.64594590e-01 -1.64594590e-01 -4.75947393e-01
 -7.35723911e-01 -9.15773327e-01 -9.96584493e-01 -9.69400266e-01
 -8.37166478e-01 -6.14212713e-01 -3.24699469e-01 -2.44929360e-16]


#### random.Generator.random(*size=None*, *dtype=np.float64*, *out=None*)

In [21]:
import numpy as np

random_generator = np.random.default_rng()

numpy.random.Generator를 생성하면 이 생성자는 0 이상 1 미만의 숫자를 사이즈에 맞춰 랜덤하게 생성합니다. 

In [22]:
random_ndarray = random_generator.random((3,5))
print(random_ndarray)

[[0.53187687 0.24753069 0.8415806  0.33491415 0.95319416]
 [0.78047545 0.4550855  0.83770085 0.46181063 0.73047089]
 [0.26515376 0.83686476 0.0259365  0.71791437 0.04654027]]


만약 a 이상 b 미만의 랜덤 ndarray를 생성하고 싶을 경우 `(b - a) * random() + a`로 대체합니다.

In [23]:
random_ndarray_from_10_to_20 = (20 - 10) * random_generator.random((3,5)) + 10
print(random_ndarray_from_10_to_20)

[[15.16857258 19.05273432 17.72303195 19.52398622 10.29145378]
 [16.29935731 10.23318736 12.37277612 18.50328899 16.8032973 ]
 [17.55816609 18.37207885 19.96944212 13.14402903 10.14294328]]


#### random.Generator.normal(loc=0.0, scale=1.0, size=None, dtype=np.float64, out=None)

In [25]:
import numpy as np

random_generator = np.random.default_rng()

`random.Generator.normal`은 정규 분포를 따르는 랜덤 숫자를 생성하는 함수입니다. `loc`는 정규 분포의 평균을 나타내며, `scale`은 표준 편차를 나타냅니다. `size`는 생성할 랜덤 숫자의 개수나 배열의 형태를 지정합니다. `dtype`은 생성된 배열의 데이터 타입을 지정하며, 기본값은 `np.float64`입니다. `out` 매개변수는 결과를 저장할 배열을 지정하는 데 사용됩니다.

In [ ]:
# 평균이 0이고 표준 편차가 1인 정규 분포(표준 정규 분포)를 따르는 랜덤 숫자 15 개 생성
normal_random_ndarray = random_generator.normal(loc=0.0, scale=1.0, size=(3, 5))
print(normal_random_ndarray)

[[-1.48196142  0.79381829  0.53137838  0.68751077 -0.46558843]
 [-0.1963227  -0.03685422 -0.11820057 -0.1201648  -1.04308479]
 [ 1.03011008 -0.31983031  0.98952471  1.36452804 -0.98921047]]
