In [6]:
import numpy as np
import time

# 문제 설정
# 2,000만 개의 요소를 가진 1차원 데이터셋을 생성합니다.
# 엑셀 시트로 치면 2,000만 개의 행을 가진 단일 열 데이터라고 생각할 수 있습니다.
data_size = 20_000_000
scalar_a = 0.5
scalar_b = 10

# --------------------
# 1. 일반 Python 리스트와 반복문 사용
# --------------------
print("1. 일반 Python 리스트로 연산 시작...")
python_data = list(range(data_size))
start_time_python = time.time()

result_python = []
for x in python_data:
    result_python.append(scalar_a * x + scalar_b)

end_time_python = time.time()
print(f"일반 Python 연산 소요 시간: {end_time_python - start_time_python:.4f} 초")
print("-" * 30)

# --------------------
# 2. numpy 배열과 벡터화된 연산 사용
# --------------------
print("2. numpy 배열로 연산 시작...")
numpy_data = np.arange(data_size)
start_time_numpy = time.time()

# numpy의 벡터화된 연산은 반복문 없이 한 줄로 처리됩니다.
result_numpy = scalar_a * numpy_data + scalar_b

end_time_numpy = time.time()
print(f"numpy 연산 소요 시간: {end_time_numpy - start_time_numpy:.4f} 초")
print("-" * 30)

# --------------------
# 결과 비교
# --------------------
# 두 결과가 동일한지 확인합니다.
if np.allclose(result_python, result_numpy):
    print("두 결과가 동일합니다.")
else:
    print("결과가 다릅니다.")

# 요약
print(f"numpy가 {(end_time_python - start_time_python) / (end_time_numpy - start_time_numpy):.2f}배 빠릅니다.")

1. 일반 Python 리스트로 연산 시작...
일반 Python 연산 소요 시간: 2.4747 초
------------------------------
2. numpy 배열로 연산 시작...
numpy 연산 소요 시간: 0.0841 초
------------------------------
두 결과가 동일합니다.
numpy가 29.44배 빠릅니다.


In [ ]:
x = [1, 2, 3, 4, 5]
y = [6, 7, 8, 9, 10]

x_np = np.array(x)
y_np = np.array(y)
result_np = x_np * 2 + y_np
print(result_np)

[ 8 11 14 17 20]
15


In [10]:
data = [10, 25, 30, 45, 50, 55, 60, 75, 80]

data_np = np.array(data)

result_np = np.where(data_np >= 50, data_np * 1.1, data_np)
print(result_np)

[10.  25.  30.  45.  55.  60.5 66.  82.5 88. ]


In [11]:
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
vector = [10, 20, 30]

matrix_np = np.array(matrix)
vector_np = np.array(vector)

result_np = matrix_np + vector_np
print(result_np)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [13]:
import numpy as np
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

result_np = np.where(data <= 40, data * 2, data - 10)
print(result_np)

[[20 40 60]
 [80 40 50]
 [60 70 80]]


In [15]:
sales = np.array([100, 150, 200, 120, 180])
costs = np.array([80, 120, 150, 90, 140])

profits = sales - costs
print(profits)

mean_profit = np.mean(profits)
median_profit = np.median(profits)
vairance_profit = np.var(profits)
print(f"평균 이익: {mean_profit}, 중앙값 이익: {median_profit}, 분산: {vairance_profit}")

[20 30 50 30 40]
평균 이익: 34.0, 중앙값 이익: 30.0, 분산: 104.0


In [24]:
import numpy as np

# A, B, C 캠페인의 노출 수, 클릭 수, 전환 수
campaign_data = np.array([
    [1000000, 5000, 100],  # A 캠페인: Impressions, Clicks, Conversions
    [1200000, 4800, 150],  # B 캠페인
    [800000, 6400, 120]   # C 캠페인
])

CTR_np = campaign_data[:, 1] / campaign_data[:, 0] * 100  # 클릭률(CTR) 계산
CVR_np = campaign_data[:, 2] / campaign_data[:, 1] * 100  # 전환율(CVR) 계산

print(CTR_np)
print(CVR_np)
print(campaign_data[np.where(CVR_np == max(CVR_np))[0][0]])

[0.5 0.4 0.8]
[2.    3.125 1.875]
[1200000    4800     150]


In [88]:
a = np.linspace(10000, 10099, 100, dtype=int)
print(a)
b = np.random.randint(2000, 35000, 100)
print(b)
c = np.random.randint(1, 100, 100)
print(c)
d = np.random.randint(1, 30, 100)/100
print(d)
e = b / c
print(e)

[10000 10001 10002 10003 10004 10005 10006 10007 10008 10009 10010 10011
 10012 10013 10014 10015 10016 10017 10018 10019 10020 10021 10022 10023
 10024 10025 10026 10027 10028 10029 10030 10031 10032 10033 10034 10035
 10036 10037 10038 10039 10040 10041 10042 10043 10044 10045 10046 10047
 10048 10049 10050 10051 10052 10053 10054 10055 10056 10057 10058 10059
 10060 10061 10062 10063 10064 10065 10066 10067 10068 10069 10070 10071
 10072 10073 10074 10075 10076 10077 10078 10079 10080 10081 10082 10083
 10084 10085 10086 10087 10088 10089 10090 10091 10092 10093 10094 10095
 10096 10097 10098 10099]
[25833 26232 30893 18472  8886  4011 12852 25254 19253  4591 27942  5765
 16523 17543  4621  4600 19717 21969 22419 26156 24630  6909  3794 22657
 21255 24928 34156 17245  8846  9665 13916 15982 27972  5396 30245 19924
 32743  3939  3265  5648 16604 26276 19954 18777 21002 12370 17563 16595
 16587 26233 27630 24038 14518 23125 33007 31963 32536 19488 27343  2345
 15431 34666 34244  5952 

In [89]:
matrix = np.column_stack((a, b, c, d, e))
matrix

array([[1.00000000e+04, 2.58330000e+04, 1.60000000e+01, 6.00000000e-02,
        1.61456250e+03],
       [1.00010000e+04, 2.62320000e+04, 7.90000000e+01, 1.30000000e-01,
        3.32050633e+02],
       [1.00020000e+04, 3.08930000e+04, 8.60000000e+01, 2.10000000e-01,
        3.59220930e+02],
       [1.00030000e+04, 1.84720000e+04, 3.00000000e+01, 2.10000000e-01,
        6.15733333e+02],
       [1.00040000e+04, 8.88600000e+03, 2.40000000e+01, 2.30000000e-01,
        3.70250000e+02],
       [1.00050000e+04, 4.01100000e+03, 6.80000000e+01, 2.80000000e-01,
        5.89852941e+01],
       [1.00060000e+04, 1.28520000e+04, 6.60000000e+01, 2.20000000e-01,
        1.94727273e+02],
       [1.00070000e+04, 2.52540000e+04, 6.60000000e+01, 5.00000000e-02,
        3.82636364e+02],
       [1.00080000e+04, 1.92530000e+04, 5.10000000e+01, 1.90000000e-01,
        3.77509804e+02],
       [1.00090000e+04, 4.59100000e+03, 9.90000000e+01, 2.90000000e-01,
        4.63737374e+01],
       [1.00100000e+04, 2.7942

In [90]:
consumer_price_index = matrix[:, 1] / matrix[:, 4] * matrix[:, 2]
print(consumer_price_index)

[2.560e+02 6.241e+03 7.396e+03 9.000e+02 5.760e+02 4.624e+03 4.356e+03
 4.356e+03 2.601e+03 9.801e+03 5.476e+03 2.250e+02 9.000e+02 7.056e+03
 3.136e+03 8.410e+02 4.900e+01 1.225e+03 2.304e+03 8.410e+02 9.025e+03
 1.089e+03 2.704e+03 6.250e+02 8.836e+03 8.410e+02 4.000e+02 2.500e+01
 4.900e+01 9.025e+03 6.250e+02 6.760e+02 3.364e+03 1.600e+01 2.209e+03
 1.000e+00 8.410e+02 3.721e+03 3.249e+03 8.100e+03 9.610e+02 8.649e+03
 1.156e+03 7.056e+03 7.569e+03 1.089e+03 9.801e+03 8.100e+01 1.225e+03
 7.569e+03 4.489e+03 3.721e+03 8.100e+01 4.900e+01 3.481e+03 9.801e+03
 4.410e+02 9.409e+03 5.184e+03 8.100e+01 6.760e+02 7.569e+03 7.396e+03
 6.400e+03 7.840e+02 6.889e+03 9.604e+03 7.840e+02 4.000e+00 8.100e+01
 1.024e+03 1.440e+02 6.250e+02 7.290e+02 1.000e+00 9.000e+00 3.721e+03
 6.241e+03 3.844e+03 1.210e+02 2.809e+03 2.250e+02 5.329e+03 9.610e+02
 8.836e+03 2.209e+03 3.364e+03 2.601e+03 3.481e+03 2.250e+02 4.840e+02
 1.089e+03 1.936e+03 1.764e+03 1.000e+02 2.401e+03 2.500e+03 3.969e+03
 2.601

In [94]:
customer_loyalty_index = np.log(matrix[:, 4] + 1) * (1 + matrix[:, 3])
print(customer_loyalty_index)

[ 7.83068478  6.56337282  7.12292822  7.77356845  7.2777571   5.24044728
  6.43760111  6.24717989  7.06412795  4.97690773  7.42058245  7.02584834
  7.19696279  5.50676141  4.91181712  6.18881638  9.05579668  7.92566671
  7.62426627  7.21398495  6.89649965  6.52558191  5.50853787  7.3552872
  6.29353986  7.16307062  8.41120771  8.3090521   7.35687956  5.51228324
  7.71493058  6.93656713  6.42781114  8.36111745  6.66254607 12.57265774
  7.45183598  5.31263324  4.67506168  5.36002266  7.47947961  5.98618556
  7.33300588  6.98410486  6.58871849  6.34422912  6.53190409  9.70102489
  7.64228658  6.56900271  6.98828865  6.51716642  8.34678985  9.56161324
  7.91090425  7.45659597  7.41968749  6.31629184  6.23928844  6.29031078
  7.85689648  6.4693221   6.10921614  4.97122837  7.02765813  6.33233351
  4.3170815   7.33488466 11.56627081  9.77338278  6.59258592  9.13808834
  7.39663934  6.2175535  11.00662887 10.40499466  5.93016354  5.68859342
  6.22209748  8.81922311  5.62885209  6.38142657  6.